# configure location of git repository where we are going to store all
# our configuration files.
spring:
    config:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/podisto/siva-microservices-config-repo
                    clone-on-start: true

server:
    port: 8888

management:
    endpoints:
        web:
            exposure:
                include: *
